[env:TTGOT7]
platform = espressif32
board = ttgo-t7-v14-mini32
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
lib_deps = 
	adafruit/Adafruit AHRS@^2.3.2
	adafruit/Adafruit LSM9DS1 Library@^2.1.1
	https://github.com/sandeepmistry/arduino-CAN
build_flags = 
	-D BOARD_HAS_PSRAM

[env:test_output]
platform = espressif32
board = ttgo-t7-v14-mini32
framework = arduino
lib_deps =
	https://github.com/sandeepmistry/arduino-CAN
build_src_filter = +<test_output.cpp> -<main.cpp>